### ISSUE TITLE
versus2coop建议更改实现方式

### ISSUE THREAD

**Issue by fantasylidong** [Sglight/l4d2-scriptings#5]
建议使用钵钵鸡写的[versus_coop_mode](https://github.com/umlka/l4d2/tree/main/versus_coop_mode)来代替以前的实现方式
在保持对抗模式的情况下，能保持地图依旧为versus地图，不再需要切换模式来避免分数版
confogl_addcvar versus_round_restarttimer 1
confogl_addcvar versus_round_restarttimer_finale 1
并且修改这两个值能快速重启当前回合

唯一一个缺点是过关总结会是所有回合的总共数据

**Comment by Sglight** [comment]
感谢提供相关帮助，不过我是大概率不会再更新这套插件了，先打个 enhancement 标签。
